glideJs = "https://cdn.jsdelivr.net/npm/@glidejs/glide"
glideCss = "https://cdn.jsdelivr.net/npm/@glidejs/glide@3.6.0/dist/css/glide.core.min.css"
googleapis = "https://fonts.googleapis.com"
gstatic = "https://fonts.gstatic.com"
gFontTitle = "https://fonts.googleapis.com/css2?family=Fira+Sans:wght@700&display=swap"
gFontContent = "https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@500;700&display=swap"
masonry = "https://unpkg.com/masonry-layout@4/dist/masonry.pkgd.min.js"





